name: Prose lint checks
on:
  pull_request:
  push:

jobs:
  vale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v23
    - name: Vale
      run: nix run nixpkgs#vale -- --glob='*.md' .
